name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Install DFINITY Canister SDK"
      run: |
        wget -O install-dfx.sh https://sdk.dfinity.org/install.sh
        yes Y | DFX_VERSION=0.6.24 bash install-dfx.sh
        echo "::add-path::/home/runner/bin"
    - name: "run"
      run: ./run.sh
